;;; configurations
((host . "::")
 (port . 443)
 (proxy-key . "Meng")
 (secret . "quanyec")
 (http-flag . "httpUDP")
 (tcp-buffer-size . 8192)
 (tcp-queue-size . 120)
 (buffer-pool-fixed? . #t)
 (heap-reserve-ratio . 0.8)
 (logger-on? . #f))
